# Generated by Django 4.2.1 on 2025-11-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_add_extra_los"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="class_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="entry_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="letter_grade",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
