# Generated by Django 4.2.1 on 2025-11-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_enrollment_grade_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programoutcome",
            name="code",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="learningoutcome",
            name="code",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_number",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="assessmentcomponent",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
