# Generated by Django 4.2.1 on 2025-11-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0007_add_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="year",
            field=models.PositiveSmallIntegerField(db_index=True, default=2023),
        ),
        migrations.CreateModel(
            name="CoursePOHeatmap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("avg_weight", models.FloatField(default=0)),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="po_heatmap", to="assessment.course")),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_heatmap",
                        to="assessment.programoutcome",
                    ),
                ),
            ],
            options={
                "ordering": ["course__code", "program_outcome__code"],
                "unique_together": {("course", "program_outcome")},
            },
        ),
    ]
